name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.13.0
      
      - name: Build release
        run: zig build release

      - name: Archive executables
        run: |
          mkdir -p artifacts
          for binary in zig-out/*; do
            filename=$(basename "$binary")
            if [[ "$filename" == *windows* ]]; then
              zip -j artifacts/"${filename}.zip" "$binary"
            else
              tar -czvf artifacts/"${filename}.tar.gz" -C zig-out "$filename"
            fi
          done
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: zvm-artifacts
          path: |
            artifacts/*.zip
            artifacts/*.tar.gz

  # This job will need to be modified to handle multiple artifacts
  create-release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Download all artifacts dynamically
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: zvm-artifacts
          path: artifacts/

      - name: List artifacts
        run: ls -la artifacts/

      - name: Create and Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "artifacts/*.tar.gz"
          artifactErrorsFailBuild: true
          generateReleaseNotes: true
          tag: ${{ github.ref }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
